[1051] Add documentation for configuration of smartrest templates
thin-edge/thin-edge.io pull request #1147
Opened 2022-05-18 12:56 UTC by makr11st

Signed-off-by: Lukasz Woznicki <lukasz.woznicki@softwareag.com>

## Proposed changes

Documentation for Custom Smartrest templates configuration.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [x] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

2022-05-18 14:59 UTC, didier-wenzek commented on docs/src/howto-guides/023_smartrest_templates.md
> +```
```suggestion
A template named `$TEMPLATE_NAME` is requires the following subscriptions to be added when connecting Cumulocity:

```plain
s/dc/$TEMPLATE_NAME
s/uc/$TEMPLATE_NAME
``

__This is not done automatically and the custom templates have to be declared using the `tedge` command__.
````

2022-05-19 11:03 UTC, albinsuresh commented on docs/src/howto-guides/023_smartrest_templates.md
> +> For example we have following template `template-1` already in our configuration
```suggestion
> Note: To add/append a new template to a device that's already configured with some, all the existing templates should also be declared along with the new one in the `tedge config set` command.
> For example, if `template-1` is already configured on the device, as follows:
```

2022-05-19 17:44 UTC, didier-wenzek approved these changes
Approved

2022-05-20 11:32 UTC, rina23q requested changes
The content looks good. However, for those reasons, I would block merging.
1. Broken format in `023_smartrest_templates.md`
2. Must add it to `docs/src/SUMMARY.md`. This is the reason why doc check failed.
```
error: It looks like "howto-guides/023_smartrest_templates.md" wasn't included in SUMMARY.md
   ┌─ howto-guides/index.md:24:5
   │
24 │ 22. [How to add C8Y SmartRest Templates](./023_smartrest_templates.md)
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ It looks like "howto-guides/023_smartrest_templates.md" wasn't included in SUMMARY.md
```

2022-05-20 11:32 UTC, rina23q commented on docs/src/howto-guides/023_smartrest_templates.md
> +# How to use C8Y Custom SmartRest 2 Templates
To be more precise,
```suggestion
# How to use Cumulocity Custom SmartREST 2.0 Templates
```

2022-05-20 11:32 UTC, rina23q commented on docs/src/howto-guides/023_smartrest_templates.md
> +``
The format of this block seems broken.
Line 12 has four backticks and line 15 has two.

2022-05-20 11:32 UTC, rina23q commented on docs/src/howto-guides/023_smartrest_templates.md
> +````
Also having 4 backticks instead of 3.

2022-05-20 11:32 UTC, rina23q commented on docs/src/howto-guides/023_smartrest_templates.md
> +When these templates are configured with thin-edge.io, subscriptions to all these relevant topics on Cumulocity cloud will be done by thin-edge internally. Local processes on the device can access th
To keep consistency of `thin-edge.io`. 
```suggestion
When these templates are configured with thin-edge.io, subscriptions to all these relevant topics on Cumulocity cloud will be done by thin-edge.io internally. Local processes on the device can access these templates on the local MQTT broker by simply publishing to `c8y/s/uc/<template-name>` and subscribing to `c8y/s/dc/<template-name>` topics (note the `c8y/` prefix in topics).
```

2022-05-20 12:25 UTC, albinsuresh commented on docs/src/howto-guides/023_smartrest_templates.md
> +s/uc/$TEMPLATE_NAME
I don't think a subscription to this `s/uc` topic is needed. `s/uc` is used only for publishing data. `s/dc` is the one that must be subscribed to.

2022-05-20 12:27 UTC, albinsuresh commented on docs/src/howto-guides/023_smartrest_templates.md
> +```
This suggestion might still be relevant as it mentions the local bridged topics that the end-user need to care about.

2022-05-23 10:46 UTC, merged