Cleanup contributing
thin-edge/thin-edge.io pull request #1384
Opened 2022-08-31 09:25 UTC by matthiasbeyer

This is the second part of #1379 and

Closes #1378

2022-08-31 09:37 UTC, TheNeikos requested changes

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +only a indicator for the seriousness of the project, but also a way to ensure
```suggestion
only an indicator for the seriousness of the project, but also a way to ensure
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +The contributor should document why they implemented a change properly. A good
```suggestion
The contributor should document why they implemented a change. A good
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +The project implements lints using github actions to meet such criteria.
```suggestion
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +Also, some hard criteria is checked via github action lints:
```suggestion
Also, some hard criteria are checked via github action lints:
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +* Body lines not longer than 72 characters
```suggestion
    * Subject line not longer than 50 characters
    * Subject capitalized
    * No period at the end of the subject
    * Imperative mood in the subject
    * Second line empty
    * Body lines not longer than 72 characters
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +but won't be merged (read more about this in the "merge strategies" section).
```suggestion
but will have to be squashed into the history before being merged.
Read more about this in the "merge strategies" section.
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +blocks pull requests to be merged if one or more of the commits of the pull
```suggestion
blocks merging pull requests if one or more of the commits of the pull
```

or 

```suggestion
blocks pull requests from being merged if one or more of the commits of the pull
```

2022-08-31 09:37 UTC, TheNeikos commented on CONTRIBUTING.md
> +* Reviews of the relevant persons (ensured via github setting)
```suggestion
* Reviews of the relevant people (ensured via github setting)
```

2022-08-31 09:42 UTC, matthiasbeyer commented on CONTRIBUTING.md
> +but won't be merged (read more about this in the "merge strategies" section).
```suggestion
but will have to be squashed by the pull request author before the being merged.
```

2022-08-31 09:48 UTC, TheNeikos commented on CONTRIBUTING.md
> +but won't be merged (read more about this in the "merge strategies" section).
remove 'the' and that's good

2022-08-31 10:47 UTC, matthiasbeyer commented
Squashed all cleanup patches.

2022-08-31 11:58 UTC, TheNeikos approved these changes

2022-09-01 09:02 UTC, didier-wenzek submitted a review, later dismissed
We need to discuss the [commit done with the false assumption there is no test team](https://github.com/thin-edge/thin-edge.io/pull/1384/commits/115d23af7811a49f088534a9645601b6de373312)

2022-09-01 09:29 UTC, matthiasbeyer commented on CONTRIBUTING.md
> -independently verify and close them.
Okay, I will push a revert for this! :+1:

2022-09-01 09:30 UTC, matthiasbeyer commented on CONTRIBUTING.md
> -[https://chris.beams.io/posts/git-commit/](https://chris.beams.io/posts/git-commit/).
Feel free to resolve this if you think [the fixup](https://github.com/thin-edge/thin-edge.io/pull/1384/commits/93056a070969d8a1f47a363ec35f62aaf5782a0f) is okay.

2022-09-01 09:32 UTC, TheNeikos commented on CONTRIBUTING.md
> +You can also read about commit message in
```suggestion
You can also read about commit messages in
```

2022-09-01 15:25 UTC, rina23q approved these changes
LGTM

2022-09-01 15:47 UTC, matthiasbeyer commented
Squashed away the fixup patches.

2022-09-06 08:22 UTC, matthiasbeyer commented
@rina23q All review points addressed as far as I can see. Feel free to merge now! :tada:

2022-09-07 15:47 UTC, didier-wenzek approved these changes
Approved

2022-09-07 15:47 UTC, didier-wenzek commented on CONTRIBUTING.md
> -independently verify and close them.
Thank you,

2022-09-07 15:47 UTC, merged