fix: use taplo for formatting Cargo.toml
thin-edge/thin-edge.io pull request #2476
Opened 2023-11-22 11:46 UTC by Bravo555

## Proposed changes

cargo-sort was replaced by taplo, which besides sorting dependencies, can also perform TOML reformatting.

New rules for formatting Cargo.toml files are:

- indent 4 spaces
- only split into multiple lines if content doesn't fit in a single line
- reorder only dependencies
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [x] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2023-11-23 07:21 UTC, albinsuresh requested changes

2023-11-23 07:21 UTC, albinsuresh commented on crates/common/tedge_config_macros/macro/Cargo.toml
> +quote = { workspace = true }
Looks like the sorting logic of `cargo-sort` was really broken, even for obvious things like this. Glad we replaced it with something more sensible.

2023-11-23 07:21 UTC, albinsuresh commented on justfile
> +    cargo install taplo-cli cargo-nextest
The following recipes are still using `cargo sort` command: `check-tools`, `format` and `format-check`.They must be replaced with `taplo fmt --check` instead, right?

2023-11-23 13:00 UTC, albinsuresh approved these changes

2023-11-24 11:42 UTC, didier-wenzek approved these changes
Approved. Thank you! Running `cargo sort` was really useless :-(

2023-11-24 15:28 UTC, jarhodes314 approved these changes
Nice to see this gives us actual TOML formatting too, not just sorting (as well as sorting in more places than we had)!

2023-11-27 08:33 UTC, merged