Fix missing supported operations #2689
thin-edge/thin-edge.io pull request #2695
Opened 2024-02-09 12:53 UTC by albinsuresh

## Proposed changes

- [Test]
- Fix

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue

https://github.com/thin-edge/thin-edge.io/issues/2689

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-02-09 12:54 UTC, albinsuresh commented on tests/RobotFramework/tasks/E2E_Tutorials/Connect_to_c8y.robot
> -    Execute Command    sudo tedge cert create --device-id ${DEVICE_SN}
Already done in the previous step.

2024-02-13 09:58 UTC, albinsuresh commented on crates/core/tedge_mapper/src/c8y/mapper.rs
> +            MqttActorBuilder::new(service_monitor_client_config(&tedge_config)?);
This MQTT actor which was previously used just to send the last will message is reused to monitor the bridge health status as well.

2024-02-13 15:12 UTC, Bravo555 requested changes
One small change required in `bootstrap.sh`

2024-02-13 15:12 UTC, Bravo555 commented on crates/core/c8y_api/src/utils.rs
note: IMO `c8y_api` crate is a bad place for bridge related utilities as name suggests the crate handles cumulocity-specific stuff, e.g. authentication, smartrest, inventory, etc.

This in itself is a low priority, but more important is that checking if the bridge is established should also work for AWS and Azure bridges, but as this change only handles cumulocity, does it mean that this issue can also appear for Azure or AWS? If so, then we should consider fixing it there as well as a follow-up.

2024-02-13 15:12 UTC, Bravo555 commented on tests/images/debian-systemd/files/bootstrap.sh
> +    --bootstrap/--no-bootstrap              Bootstrap tedge by setting c8y.url and creating and uploading the device certificate. Default True
todo: delete line 21 which also contains `--bootstrap`

2024-02-14 07:44 UTC, albinsuresh commented on crates/core/c8y_api/src/utils.rs
> note: IMO c8y_api crate is a bad place for bridge related utilities as name suggests the crate handles cumulocity-specific stuff, e.g. authentication, smartrest, inventory, etc.

I agree. I think it was added in this crate for lack of another common crate that could be accessed by all the c8y components like the mapper and other c8y plugins. But, now that the other components are gone, I don't see anything wrong with moving this into the mapper. But, that being said, this bridge itself is going to get replaced with our own bridge component in the near future. So, may not be a high priority item for now.

> This in itself is a low priority, but more important is that checking if the bridge is established should also work for AWS and Azure bridges, but as this change only handles cumulocity, does it mean that this issue can also appear for Azure or AWS? If so, then we should consider fixing it there as well as a follow-up.

The principle definitely applies to other mappers as well, that no mapping should happen until the bridge is established. But, this is less critical in the case of other mappers, in their current state, as they only map telemetry data, and not entity registrations or any other critical metadata messages. It's okay to drop a few telemetry messages before the bridge is established, as updates to them would be coming later on. But, that's not the case with other entity metadata messages which are only sent once and that's why it's far more critical for the c8y mapper.

2024-02-14 10:21 UTC, Bravo555 approved these changes

2024-02-14 10:58 UTC, merged