Fix broken simulated monitoring tests
thin-edge/thin-edge.io pull request #275
Opened 2021-06-08 02:39 UTC by PradeepKiruvale

## Proposed changes

This PR captures the code changes for fixing the broken system tests.

**Problem:**
When monitoring with simulated messages tests triggered from GH actions the simulated messages are not getting batched as expected (all messages in one batch).  Looks like some timing issue, because of this the messages are getting batched into different batches, but we expect them to be batched together. So, we were aborting with an error if the message is not present in the current batch.

**Note:** Tests work properly when triggered/ran manually. 

**Proposed Fix:**

This fix checks if the message/telemetry present in the current batch or not, if it's present then will be validated, else skipped, will not be aborted with an error.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactorings that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-06-08 07:39 UTC, abelikt approved these changes
Looks good

2021-06-08 07:45 UTC, albinsuresh approved these changes

2021-06-08 07:59 UTC, albinsuresh requested changes

2021-06-08 07:59 UTC, albinsuresh commented on tests/PySys/monitoring/monitoring_smaller_interval/run.py
> +        return True
With these changes we need an additional validation that the temperature and pressure are appearing at least once, either in a single JSON message or split across multiple messages. But that "exactly once" logic needs to be tested.

2021-06-08 14:31 UTC, albinsuresh commented on tests/PySys/monitoring/monitoring_smaller_interval/run.py
> +        if self.time_cnt > 10 and self.temp_cnt == 10 and self.pres_cnt == 10:
Greater than **or equal to** 10, right?

2021-06-09 03:31 UTC, albinsuresh approved these changes

2021-06-09 06:42 UTC, merged