System Test for the mosquitto bug causes mqtt session persistence to be non-functional
thin-edge/thin-edge.io pull request #3187
Opened 2024-10-15 08:01 UTC by gligorisaev

Create Test Case for the "mosquitto bug causes mqtt session persistence to be non-functional" [https://github.com/thin-edge/thin-edge.io/issues/3185](https://github.com/thin-edge/thin-edge.io/issues/3185)

The test step "Check Result" will always pass but will log (actual "to Console") the result: 
"Test PASSED: MQTT flow worked as expected."
"Test FAILED: MQTT flow did not work as expected."

 The intention is to have overview if the mosquitto bug still exist.

## Proposed changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2024-10-15 08:35 UTC, reubenmiller commented on tests/RobotFramework/tests/mqtt/mosquitto_bug_check.robot
> +    Log Result    ${trimmed_result}
Just create 1 test case rather the splitting the test setup into individual test cases, and don't bother testing for the local mqtt persistence, just check if the message is delivered to the cloud or not (as this is the user contract).

So the (single) test case should do:

1. Stop the tedge-mapper-c8y
2. Publish an event
3. Start the tedge-mapper-c8y
4. Check that the event is visible in the cloud

2024-10-17 07:17 UTC, didier-wenzek commented on tests/RobotFramework/tests/mqtt/mosquitto_bug_check.robot
This test suite has to be removed. The test is green but for the wrong reason: the twin event that exists on c8y is not the event that has just been published.

=> One way to avoid such name clashes is to come with fresh new names for each test case. E.g. '{ "text": "Event sent when stopped" }'

2024-10-17 07:23 UTC, reubenmiller commented
@gligorisaev some general comments/improvements:
* Please use **fixup** commits when addressing comments explicitly related changes/problems to previously committed code (this helps keep the git commit history clean, as your second commit does not add any valuable information)

* The naming of the test suite and the filename does not suit the contract that we want to provide to users. e.g. we shouldn't be explicitly checking for the mosquitto bug, we should be checking that thin-edge.io does not lose data if a client publishes qos1 or 2 messages whilst the mapper is down (notice the commit that I pushed https://github.com/thin-edge/thin-edge.io/pull/3187/commits/54b7b0c425babf3b8ffffb36bc94a29c60f5322f)
* Prefer using **Test Setup** over **Suite Setup** unless you have a really good reason to use **Suite Setup**
* Use unique identifiers when publishing test data. This helps reduce unexpected mistakes/behaviour if whatever assertion that you're doing looks beyond the expected scope (e.g. it looks at all events in the platform instead of events for the given device)...this is the reason why your test is passing (when it shouldn't), and my test is failing (as it should)
* Use existing keywords where possible, e.g. prefer using `Stop Service` instead of manually running `sudo systemctl stop ...`. The existing library keywords help the tests to be abstracted so that we can support other service managers using the same tests (e.g. SysVinit etc.)
* Prefix the library on specific keywords where the meaning matters, for example `Cumulocity.Device Should Have Event/s` is more clear where the events are meant to be located (e.g. in Cumulocity and not on the local MQTT broker)
* Keep the PR description up to date to reflect the purpose of the changes. The purpose of the ticket is to add coverage for offline publishing (not to test a mosquitto bug)...the mosquitto bug aspect just was the motivation to add such a test...if we had had the system test prior to upgrading to mosquitto 2.0.18, the test would of shown us that 2.0.18 has an issue (ahead of time before we used it in all of our images; system test image, rugpi image, yocto image etc.)

2024-10-17 07:30 UTC, reubenmiller commented
@gligorisaev 
* Always put the linked ticket under the **Paste Link to the issue** section. You can also mention the ticket link in the description as well (if provides additional context), however having the links all in the same place makes it easier to read all the PRs and the content is normalized.

2024-10-17 12:45 UTC, reubenmiller requested changes
@gligorisaev Can you remove the following commits from the PR as they have been superseded by 54b7b0c425babf3b8ffffb36bc94a29c60f5322f:

* 84bca7153ba02ff67b85add3f539ee4613856095
* 820755e0bb25346dafe7913850d23a2946d2a3b6

And can you please update the PR description to suite (as per comments):

* https://github.com/thin-edge/thin-edge.io/pull/3187#issuecomment-2418765325
* https://github.com/thin-edge/thin-edge.io/pull/3187#issuecomment-2418776651

2024-10-18 08:45 UTC, reubenmiller submitted a review, later dismissed
@gligorisaev Thanks for dropping the two other commits, but now the commit I pushed yesterday to switch back to using mosquitto 2.0.11 is missing which means the test is failing (as the system tests are still using the bugging mosquitto 2.0.18 version)

2024-10-18 08:54 UTC, gligorisaev commented
> @gligorisaev Thanks for dropping the two other commits, but now the commit I pushed yesterday to switch back to using mosquitto 2.0.11 is missing which means the test is failing (as the system tests are still using the bugging mosquitto 2.0.18 version)

I did rebase and choose drop of my commits only (made also screenshot of it)

2024-10-18 11:00 UTC, reubenmiller commented on tests/RobotFramework/tests/mqtt/mosquitto_bug_check.robot
The test has been refactored to use a unique event type, 4d9741de6d59d498e1300521407ccd3d1098b970

2024-10-18 11:58 UTC, reubenmiller reviewed
I've removed my review from this PR as the commits are authored by myself, so I shouldn't be the one approving it.

2024-10-18 12:06 UTC, reubenmiller commented
> > @gligorisaev Thanks for dropping the two other commits, but now the commit I pushed yesterday to switch back to using mosquitto 2.0.11 is missing which means the test is failing (as the system tests are still using the bugging mosquitto 2.0.18 version)
> 
> I did rebase and choose drop of my commits only (made also screenshot of it)

Then something went very wrong (maybe you didn't do a fetch and pull prior to rebasing). But anyway I've forced pushed the changes that I still had locally.

2024-10-18 12:37 UTC, didier-wenzek approved these changes
Approved

2024-10-18 20:51 UTC, merged