[CIT-522] Smagent should use proper mqtt port
thin-edge/thin-edge.io pull request #392
Opened 2021-08-19 07:14 UTC by PradeepKiruvale

## Proposed changes

This PR captures the code changes required for smagent to use the proper mqtt port.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactorings that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
<br/>

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2021-08-19 07:31 UTC, albinsuresh reviewed
This PR has a fundamentally different approach to how the port is read from the `TEdgeConfig` compared to #386. These changes make the agent more and more dependent on the `TEdgeConfig` whereas PR #386 is trying to do the exact opposite. So, it would be better if this PR is adapted once #386 is merged.

2021-08-19 08:01 UTC, didier-wenzek reviewed
This PR takes a different approach to read the tedge config compared to what is proposed by https://github.com/thin-edge/thin-edge.io/pull/386.

The two PRs must be aligned. I think the approach taken here is less invasive and I advocate for this PR to be taken as the base.

2021-08-19 08:29 UTC, didier-wenzek commented on sm/tedge_agent/src/agent.rs
> +                .with_port(tedge_config.query(MqttPortSetting)?.into()),
After discussion with @albinsuresh  and @PradeepKiruvale, the proper place to read the tedge config is in `SmAgentConfig::new(tedge_config_location)` and then to build an agent with `SmAgent::new(sm_agent_config)`.

2021-08-19 15:48 UTC, didier-wenzek requested changes

2021-08-19 15:48 UTC, didier-wenzek commented on sm/tedge_agent/src/main.rs
> +
Can you please move all this code in a `SmAgentConfig::new(tedge_config_location)` method taking a tedge config as an argument.

2021-08-20 13:53 UTC, didier-wenzek approved these changes
Approved

2021-08-20 14:28 UTC, merged