[CIT-561] Add aarch64 and arm64 support to install script
thin-edge/thin-edge.io pull request #413
Opened 2021-09-02 08:31 UTC by makr11st

## Proposed changes

Add support for `aarch64` and `arm64` architectures in the install script.
Adding the download files to the release is required before merging.

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [ ] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

2021-09-02 14:00 UTC, albinsuresh approved these changes

2021-09-02 14:05 UTC, makr11st commented on get-thin-edge_io.sh
> +# Packages for `arm64` are zipped in files with `aarch64` in names.
I see the comment doesn't give the actual situation the justice.
Your observation is correct, there are no aarch64/arm64 packages in the release at the moment, that's why I made a comment in the description that it shouldn't be merged before those files are merged, additionally there is no aarch64/arm64 packages available before 0.3.0, therefore I think an additional check for version should be applied, but I need to discuss this with Sebastian before, as this is not in the ticket.

2021-09-03 06:33 UTC, albinsuresh commented on get-thin-edge_io.sh
> +# Packages for `arm64` are zipped in files with `aarch64` in names.
Okay. I thought the same `amd64` binaries can be used even on the systems reporting `aarch64` and `arm64`. So, we're going to create new packages for these archs as well, named after them?

2021-09-03 07:40 UTC, itsyitsy commented on get-thin-edge_io.sh
> +# Packages for `arm64` are zipped in files with `aarch64` in names.
Having aarch64/arm64 support only after version 0.3.0 seems ok. Just uploaded the arm64 package to the latest release

2021-09-03 12:26 UTC, itsyitsy requested changes

2021-09-03 12:26 UTC, itsyitsy commented on get-thin-edge_io.sh
> +
As discussed in our chat this morning

2021-09-03 12:26 UTC, itsyitsy commented on get-thin-edge_io.sh
> +
Please remove this, also as discussed

2021-09-03 17:14 UTC, albinsuresh approved these changes

2021-09-03 17:14 UTC, albinsuresh commented on get-thin-edge_io.sh
> +    # For arm64 only version versions above 0.3.0 are available.
```suggestion
    # For arm64, only the versions above 0.3.0 are available.
```

2021-09-03 17:14 UTC, albinsuresh commented on get-thin-edge_io.sh
> +        echo "aarch64/arm64 can only be installed with version 0.3.0 or above."
```suggestion
        echo "aarch64/arm64 compatible packages are only available for version 0.3.0 or above."
```

2021-09-07 12:07 UTC, itsyitsy approved these changes

2021-09-07 12:19 UTC, merged