single config file for tedge command (#814)
thin-edge/thin-edge.io pull request #899
Opened 2022-02-17 16:37 UTC by initard

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Acceptance Criteria:
- [ ] Do not change the daily usage of `sudo tedge` and other daemons: `/etc/tedge` is still the implicit thin-edge configuration directory.
- [ ] Make `tedge` (without `sudo`) use the same `/etc/tedge` config files, obviously without write permissions.
- [ ] Add a `--config-dir` option to the `tedge` command as well as to the mappers and the agent.
- [ ] The argument of this `--config-dir` option is the path to a directory with a `tedge.toml` file and the other configuration files expected by thin-edge.
- [ ] The default value for this `--config-dir` option is `/etc/tedge`.
- [x] removed if/else tedge_config::TEdgeConfigLocation::from_users_home_location logic
    from tedge main.rs

## Types of changes

What types of changes does your code introduce to `thin-edge.io`?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)
- [ ] Documentation Update (if none of the other choices apply)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Paste Link to the issue
#814 

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2022-02-22 06:25 UTC, PradeepKiruvale commented on crates/core/tedge/tests/main.rs
> +        assert!(key_path.contains(&test_home_str));
Maybe this has been cert_path?

2022-02-22 06:38 UTC, matthiasbeyer requested changes

2022-02-22 06:38 UTC, matthiasbeyer commented on crates/common/tedge_config/src/tedge_config_location.rs
> +    pub fn from_custom_location(custom_etc_path: impl AsRef<Path>) -> Self {
Isn't this just a duplicate of `TEdgeConfigLocation::from_custom_root()`? Why duplicate it?

2022-02-22 06:38 UTC, matthiasbeyer commented on crates/common/tedge_config/src/tedge_config_location.rs
> +        Self::from_custom_root(Path::new(DEFAULT_ETC_PATH))
This looks a lot like it could be moved to a `Default` implementation.

2022-02-22 06:38 UTC, matthiasbeyer commented on crates/common/tedge_config/src/tedge_config_location.rs
> +pub const DEFAULT_ETC_PATH: &str = "/etc/tedge";
I agree with @PradeepKiruvale that this should be named with a more explanatory name. Their suggestion (`DEFAULT_TEDGE_CONFIG_PATH`) seems right!

2022-02-23 02:44 UTC, PradeepKiruvale reviewed
I feel its good to add a system test with --config-dir which covers `tedge` , `tedge mapper` and `tedge_agent`. Just to make sure the these components work with the new config-dir option

2022-02-23 06:54 UTC, matthiasbeyer approved these changes
Diff looks good to me :+1:

2022-02-23 09:24 UTC, merged