Add note about fixup commits
thin-edge/thin-edge.io pull request #922
Opened 2022-02-22 07:43 UTC by matthiasbeyer

## Proposed changes

This patch adds a note about "fixup-commits".

I noticed that we still see some commits that are addressing review comments that could potentially be squashed into other commits before merging a PR.
Right now, this is not yet that much of an issue because these PRs are still squash-merged. As soon as we move fully away from squash merging, these kind of commits can be squashed away by the author of the PR as soon as a PR passes review (and CI of course).

This patch adds to the `CONTRIBUTING` documentation for this to be documented.

## Types of changes

- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)

## Further comments

This is probably a bit controversial, so I'm opening this as a draft for now, opening up for discussion here. :smiley: :sunny:

2022-02-22 08:15 UTC, TheNeikos requested changes

2022-02-22 08:15 UTC, TheNeikos commented on CONTRIBUTING.md
> +"Fixup-commits" should then be squashed
```suggestion
These fixup commits should then be squashed
```

2022-02-22 08:15 UTC, TheNeikos commented on CONTRIBUTING.md
> +passed all review and before it is merged.
```suggestion
passed review and before it is merged.
```

2022-02-22 10:18 UTC, didier-wenzek commented
I'm fine with this clarification. The question I would have is when is this *applicable* ? Reading this [post](https://jordanelver.co.uk/blog/2020/06/04/fixing-commits-with-git-commit-fixup-and-git-rebase-autosquash/), things are clearer now (these options were new to me ;-)) but I also think we cannot explain all the options and subtleties of git in the CONTRIBUTING guide.

2022-02-22 10:24 UTC, TheNeikos commented
@didier-wenzek 
> we cannot explain all the options and subtleties of git in the CONTRIBUTING guide

I mean, why not? Of course, duplicating information is not a great idea, but on the flipside having a link to useful information so as to educate those who wish to learn how to contribute seems like a good idea.

2022-02-22 10:28 UTC, matthiasbeyer commented
> The question I would have is when is this applicable?

Whenever a PR does not pass review and needs further patches.

2022-02-22 11:45 UTC, didier-wenzek commented
> > The question I would have is when is this applicable?
> 
> Whenever a PR does not pass review and needs further patches.

On that point I disagree. This cannot be for any patches.
* Yes, for a typo or improved code readability.
* No, when the patch addresses a point that the review highlighted as missing.

2022-02-22 11:49 UTC, matthiasbeyer commented
Yes, you're probably right, I overgeneralized here. :+1:

2022-03-07 07:55 UTC, TheNeikos approved these changes

2022-03-07 11:55 UTC, didier-wenzek approved these changes
Approved.

I'm just confused by this follow up PR https://github.com/thin-edge/thin-edge.io/pull/973.

2022-03-07 13:28 UTC, merged

2022-03-07 13:29 UTC, matthiasbeyer commented
This PR here is (was) about _developing_ of a PR, which might or might not contain fixup commits.
#973 is about _merging_ branches that contain fixup-commits, which should never happen!