Add workflow to block fixup commits
thin-edge/thin-edge.io pull request #973
Opened 2022-03-03 08:08 UTC by matthiasbeyer

## Proposed changes

This patch adds a workflow that blocks commits that were made with
`git commit --fixup` or `git commit --squash` during the development of
a PR.

For example as happened from https://github.com/thin-edge/thin-edge.io/pull/934 (no offense of course)!

## Types of changes

- [x] Improvement (general improvements like code refactoring that doesn't explicitly fix a bug or add any new functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)

2022-03-03 13:51 UTC, didier-wenzek requested changes
Honestly, I don't understand the point here, neither where you are going.

* [You requested for `--fixup`](https://github.com/thin-edge/thin-edge.io/pull/922) and now you want to block them?
* What is bad to have fixups in a PR?
* And even if this were good to avoid, I think we have more important improvements to focus on.

2022-03-03 14:05 UTC, matthiasbeyer commented
> What is bad to have fixups in a PR?

Of course you're right - it is not bad at all to have them in a PR! My PR is coming from the idea that the cleanup step must be done and shouldn't be forgotten before merging the PR!
(What I wrote [here](https://github.com/thin-edge/thin-edge.io/pull/922/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R40-R42)! The fixup commits should be rebased and squashed (`git rebase main -i --autosquash`) right before the PR is merged!

I think I was not clear enough in my communication on that part, I am sorry about that!

2022-03-07 13:40 UTC, didier-wenzek approved these changes
Approved.

It took me sometime but I finally got the point ;-)

2022-03-07 13:41 UTC, merged

2022-03-07 13:41 UTC, matthiasbeyer commented
Thanks!