# 984 Error: Couldn't acquire file lock.
thin-edge/thin-edge.io pull request #985
Opened 2022-03-08 14:12 UTC by initard

## Proposed changes

- fixed /run path bug introduced by #939
- updated /run default configuration to use /run

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
## Paste Link to the issue
<br/>

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://github.com/thin-edge/thin-edge.io/blob/main/CONTRIBUTOR-LICENSE-AGREEMENT.md) (in all commits with git commit -s)
- [x] I ran `cargo fmt` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I used `cargo clippy` as mentioned in [CODING_GUIDELINES](https://github.com/thin-edge/thin-edge.io/blob/main/CODING_GUIDELINES.md)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

2022-03-08 15:29 UTC, abelikt approved these changes
Looks good :)

2022-03-08 21:36 UTC, rina23q commented on crates/common/tedge_config/src/tedge_config.rs
> +            .unwrap_or_else(|| self.config_defaults.default_run_path.clone()))
Flock files should be created under `/run/lock`. Doesn't this return only `/run/`?

2022-03-08 21:47 UTC, rina23q requested changes
Unfortunately, my question was true. I tested, then it uses `/run/tedge-mapper-c8y.lock` instead of `/run/lock/tedge-mapper-c8y.lock`.

```
$ sudo -u tedge-mapper ./tedge_mapper c8y
2022-03-08T21:46:35.325923843Z ERROR flockfile::unix: Another instance of tedge-mapper-c8y is running.
2022-03-08T21:46:35.325976232Z ERROR flockfile::unix: Lock file path: /run/tedge-mapper-c8y.lock
Error: Couldn't acquire file lock.

Caused by:
    Permission denied (os error 13)
```

2022-03-09 11:02 UTC, rina23q commented on crates/common/tedge_config/src/tedge_config.rs
> +            .unwrap_or_else(|| self.config_defaults.default_run_path.clone()))
P.S. This function should return just `/run`, this is what we ask for users. However, when creating a lock file, we have to postfix it to add `/lock`.

2022-03-10 14:13 UTC, merged